# This workflow build Docker container and push to Google Artifact Registry and deploy it on Cloud Run when code changes are pushed to the "dev" branch
#
# Steps:
#
# 1. Checkout
# 2. Docker Auth for Artifact Regisrty
# 3. Google auth for Artifact Registry admin access
# 4. Build docker container and push to Google Artifact Registry
# 5. Google auth for Artifact Registry write and Cloud Run deploy access
# 6. Deploy it to Cloud Run

name: buildDevDeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

env:
  PROJECT_ID: flexion-dev # GCP Proj id
  GAR_LOCATION: us-central1 # Artifact Registry location
  SERVICE: hello-srv # Registry artifact name
  REGION: us-central1 # update Cloud Run service region
  REPO_NAME: flexion-repository
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: _json_key
          password: ${{ secrets.GCP_REGISTRY_DEV_ACCESS_TOKEN }}

      - name: Google Registry Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_REGISTRY_DEV_ACCESS_TOKEN }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE }}:dev" ./
          docker images
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE }}:dev"
      
      - name: Google Deploy Auth
        id: authDeploy
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets. GCP_CLOUDRUN_DEV_DEPLOYER_TOKEN }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: flexion-srv-dev
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE }}:dev

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

       