# This is a basic workflow to help you get started with Actions

name: Build and Deploy to CloudRun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: scenic-shift-356222 # GCP Proj id
  GAR_LOCATION: us-central1-docker.pkg.dev/scenic-shift-356222/flexion-repository # Artifact Registry location
  SERVICE: hello-srv # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Google Registry Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_REGISTRY_ACCESS_TOKEN }}

      - name: Build and Push Container
        run: |-
          echo pwd
          docker build "${{ env.SERVICE }}" .
          docker push "${{ env.GAR_LOCATION }}"